- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    - ami_id: ami-ad8894c1
    - instance_type: m3.large
#    - instance_type: m3.xlarge
#    - instance_type: m3.2xlarge
    - instances: 1
    - aws_region: eu-central-1
    - aws_key_name: jenkins-training-key
    - aws_group: jenkins-training-group
  roles:
    - aws

- hosts: "{{ hosts_group }}"
  user: ubuntu
  become: true
  gather_facts: true
  vars:
    - user: ubuntu
  roles:
    - common
    - java
    - docker
    - docker-compose
    - registry
    - node
    - cje
    - users
    - { role: preload, when: "preload is defined" }
    - announce