- hosts: localhost
  remote_user: vagrant
  sudo: yes
  serial: 1
  roles:
    - common
    - java
    - docker
    - docker-compose
    - registry
    - node
    - cje
    - users
    - { role: preload, when: "preload is defined" }